# Generated by Django 4.2.1 on 2023-07-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
