# Generated by Django 4.2.1 on 2023-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
