# Generated by Django 4.2.1 on 2023-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0003_alter_log_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(max_length=100, verbose_name='質問のタイトル'),
        ),
    ]
