# Generated by Django 4.2.1 on 2023-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0004_alter_log_date_alter_log_text_alter_log_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
    ]
