# Generated by Django 4.2.1 on 2023-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0005_alter_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
