# Generated by Django 4.2.1 on 2023-08-17 12:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0006_log_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=30, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
