# Generated by Django 4.2.1 on 2023-08-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0007_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='ユーザー名'),
        ),
    ]
