# Generated by Django 4.2.1 on 2023-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0008_remove_log_user_log_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
