# Generated by Django 4.2.1 on 2023-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0010_remove_file_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='ユーザー名'),
        ),
    ]
